on: 
    push:
        branches: 
            - main
            - "release/**" 
        paths:
            - "src/**" 

jobs: 
  test: 
      runs-on: ubuntu-latest 
      steps: 
      - name: Checkout code 
        uses: actions/checkout@v6.0.3

      - name: Run tests 
        run:  npm test